nginx_config_file: /opt/nginx/conf/nginx.conf
nginx_bin: /opt/nginx/sbin/nginx
server_ip: 94.73.33.41
jails_dir: /usr/jails

# currently deprecated
app_nginx_config:
  listen: 80
  server_name: <name>.misho.robopartans.com
  root: var/www-data/<name>/public
app_database_config:
  adapter: mysql2
  username: root
  password: robopar #TODO
  database: <name>
  pool: 5
  timeout: 5000
app_repo: https://github.com/mzdravkov/videatra
