# docker strategie specific

nginx_config_file: /myr/nginx/conf/nginx.conf
nginx_bin: /myr/nginx/sbin/nginx
server_ip: 94.73.33.41
docker_image: fcat/rails-getting-started
myrmidon_password: myrmidon
tenants_configs_dir: /myr/configs
tenants_port: 3000
tenants_config_path: /config
tenants_default_config: /myr/tenant_conf.default.yml
#docker_run_options:
#docker_entry_command:
nginx_location_resolver: 8.8.8.8

# FreeBSD jails specific
# currently not working
##########################
#nginx_config_file: /etc/nginx/nginx.conf
#nginx_bin: /usr/sbin/nginx
#server_ip: 94.73.33.41
#jails_dir: /usr/jails
##########################
